name: Terraform Deployment
on: push
jobs:
  deploy:
    env:
      AWS_ACCESS_KEY_ID: "${f secrets.AWS_ACCESS_KEY_ID }}"
      AWS_SECRET_ACCESS_KEY: "${f secrets.AWS_SECRET_ACCESS_KEY }}"
      AWS_SESSION_TOKEN: "${f secrets.AWS_SESSION_TOKEN }}"
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v4
    - name: Set Up Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.12.2
    - name: Terraform Init, Plan
      run:
        terraform init
        terraform plan
    - name: Terraform Apply
      run: terraform apply -auto-approve